páginas para redefinir a senha
joaovitro99/Aluguel-de-carros pull request #30
Opened 2024-11-08 01:31 UTC by Mayconncs

Este Pull Request implementa a funcionalidade de redefinição de senha para os usuários. A funcionalidade inclui:

Solicitação de redefinição de senha:

O usuário pode solicitar a redefinição de senha por meio de um formulário com o campo de e-mail.
O sistema envia um e-mail com um link único para redefinir a senha.
Redefinir a senha:

O usuário pode acessar o link enviado por e-mail, que redireciona para uma página onde ele pode definir uma nova senha.
A nova senha é validada (mínimo de 8 caracteres, contendo letras e números).
Validação do link de redefinição:

O link enviado por e-mail contém um token único que é validado no momento em que o usuário acessa o link.
O token é expirado após um determinado período (ex.: 1 hora) ou já foi usado.
Alteração da senha:

A senha é atualizada no banco de dados se a validação for bem-sucedida.
O usuário recebe uma notificação sobre a mudança de senha.

2024-11-08 01:40 UTC, VicthorCM commented
Só fazer o merge depois de atualizar a develop remota

2024-11-08 12:53 UTC, VicthorCM requested changes
Explicar a alteração no composer

2024-11-08 12:53 UTC, VicthorCM commented on vendor/composer/installed.php
Por que esta alteração no composer? Isso pode causar algum problema de compatibilidade?

2024-11-08 14:01 UTC, Mayconncs commented on vendor/composer/installed.php
Essa alteração foi realizada ao instalar a biblioteca do PHPMailer no meu local. As referências só foram atualizadas, você poderia ainda, apenas voltar às referências antigas. E quanto a outra pergunta, não causa incompatibilidade.

2024-11-11 01:54 UTC, joaovitro99 commented on vendor/composer/installed.php
pq ces tao digitando igual clt que ja vendeu a alma

2024-11-11 01:56 UTC, joaovitro99 approved these changes

2024-11-11 01:56 UTC, joaovitro99 commented on app/views/Login.php
maluco mexeu em tudo memo vei

2024-11-11 01:56 UTC, merged